PaintingStore/Pages/Paintings/Basket.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PaintingStore.Models;
using PaintingStore.Services;

namespace PaintingStore.Pages.Paintings
{
    public class BasketModel : PageModel
    {
        private readonly IBasketRepository _basketRepository;
        public List<Painting> paintingsInBasket;
        public int quantity;

        public BasketModel(IBasketRepository basketRepository)
        {
            _basketRepository = basketRepository;
        }

        public IActionResult OnGet(int? id)
        {
            if (id.HasValue)
            {
                paintingsInBasket = _basketRepository.AddToBasket(id.Value);
                quantity = paintingsInBasket.Count();
            }
            else
            {
                paintingsInBasket = _basketRepository.GetAllBasket();
            }

            return Page();
        }
    }
}

PaintingStore/Pages/Paintings/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PaintingStore.Models;
using PaintingStore.Services;

namespace PaintingStore.Pages.Paintings
{
    public class DeleteModel : PageModel
    {
        private readonly IPaintingRepository _paintingRepository;

        public DeleteModel(IPaintingRepository paintingRepository)
        {
            _paintingRepository = paintingRepository;
        }

        [BindProperty]
        public Painting Painting { get; set; }

        public IActionResult OnGet(int id)
        {
            Painting = _paintingRepository.GetPainting(id);

            if (Painting == null)
            {
                return RedirectToPage("/NotFound");
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            Painting deletedPainting = _paintingRepository.Delete(Painting.Id);

            if (deletedPainting == null)
            {
                return RedirectToPage("/NotFound");
            }

            return RedirectToPage("Paintings");
        }
    }
}

PaintingStore/Pages/Paintings/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PaintingStore.Services;
using PaintingStore.Models;

namespace PaintingStore.Pages.Paintings
{
    public class DetailsModel : PageModel
    {
        private readonly IPaintingRepository _paintingRepository;

        public DetailsModel(IPaintingRepository paintingRepository)
        {
            _paintingRepository = paintingRepository;
        }

        public Painting painting { get; private set; }

        public IActionResult OnGet(int id)
        {
            painting = _paintingRepository.GetPainting(id);

            if (painting == null)
            {
                return RedirectToPage("/NotFound");
            }

            return Page();
        }
    }
}

PaintingStore/Pages/Paintings/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PaintingStore.Models;
using PaintingStore.Services;
using Microsoft.Net.Http;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace PaintingStore.Pages.Paintings
{
    public class EditModel : PageModel
    {
        private readonly IPaintingRepository _paintingRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;

        [BindProperty]
        public int MaxPaintingId { get; set; }

        [BindProperty]
        public int NewPaintingId { get; set; }

        [BindProperty]
        public IFormFile Photo { get; set; }

        [BindProperty]
        public Painting Painting { get; set; }

        [BindProperty]
        public IEnumerable<Painting> Paintings { get; set; }

        public EditModel(IPaintingRepository paintingRepository, IWebHostEnvironment webHostEnvironment)
        {
            _paintingRepository = paintingRepository;
            _webHostEnvironment = webHostEnvironment;
            Paintings = _paintingRepository.GetAllPaintings();
            if (Paintings.Count() > 0)
            {
                MaxPaintingId = Paintings.Max(x => x.Id);
            }
            else
            {
                MaxPaintingId = 0;
            }
        }

        public IActionResult OnGet(int? id)
        {
            if (id.HasValue)
            {
                Painting = _paintingRepository.GetPainting(id.Value);
            }
            else
            {
                Painting = new Painting();
                NewPaintingId = MaxPaintingId + 1;
            }

            if (Painting == null)
            {
                return RedirectToPage("/NotFound");
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                if (Photo != null)
                {
                    Painting.Photopath = ProcessUploadedFile();
                }

                if (NewPaintingId > MaxPaintingId)
                {
                    Painting = _paintingRepository.Add(Painting);
                }
                else
                {
                    Painting = _paintingRepository.Update(Painting);
                }

                return RedirectToPage("Paintings");
            }

                return Page();
        }

        private string ProcessUploadedFile()
        {
            string uniqueFileName = null;

            if (Photo != null)
            {
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                using (var fs = new FileStream(filePath, FileMode.Create))
                {
                    Photo.CopyTo(fs);
                }
            }

            return uniqueFileName;
        }
    }
}

PaintingStore/Pages/Paintings/Paintings.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PaintingStore.Models;
using PaintingStore.Services;

namespace PaintingStore.Pages.Paintings
{
    public class PaintingsModel : PageModel
    {
        private readonly IPaintingRepository _db;

        public PaintingsModel(IPaintingRepository db)
        {
            _db = db;
        }

        public IEnumerable<Painting> Paintings { get; set; }

        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; }

        public void OnGet()
        {
            Paintings = _db.Search(SearchTerm);
        }
    }
}

PaintingStore/Pages/Paintings/Stats.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PaintingStore.Pages.Paintings
{
    public class StatsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

PaintingStore/ViewComponents/PaintCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PaintingStore.Services;

namespace PaintingStore.ViewComponents
{
    public class PaintCountViewComponent : ViewComponent
    {
        private readonly IPaintingRepository _paintingRepository;

        public PaintCountViewComponent(IPaintingRepository paintingRepository)
        {
            _paintingRepository = paintingRepository;
        }

        public IViewComponentResult Invoke()
        {
            var result = _paintingRepository.PaintingCountByGenre();

            return View(result);
        }
    }
}

PaintingStore/Pages/Paintings/Basket.cshtml
@page
@model PaintingStore.Pages.Paintings.BasketModel
@{
    int sumPrice = 0;
}


<div>
    <div class="row">
        @if (Model.paintingsInBasket != null)
        {
            foreach (var item in Model.paintingsInBasket)
            {
                sumPrice += item.Cost;
                var photoPath = $"/images/{item.Photopath ?? "noimage.png"}";

                <div class="col-3 col-lg-3 col-sm-1 alert-success">
                    <div class="card-deck">
                        <div class="card m-3">
                            <div class="card-header text-center">
                                <h3>@item.Name</h3>
                            </div>

                            <div class="card-body text-center">
                                <img class="card-img-top" src=@photoPath asp-append-version="true" />
                            </div>

                            <div class="card-footer">
                                <h2 class="text-success"><strong class="text-dark">Price:</strong> @item.Cost $</h2>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
    </div>

    <div>
        <h2>@sumPrice $</h2>
    </div>

</div>

PaintingStore/Pages/Paintings/Delete.cshtml
@page "{id}"
@model PaintingStore.Pages.Paintings.DeleteModel
@{
    ViewData["Title"] = "Delete";

    var photoPath = $"/images/{Model.Painting.Photopath ?? "noimage.png"}";
}

<h1 class="text-center justify-content-center">Delete Confirmation</h1>

<div class="alert alert-danger">
    <div class="row">
        <div class="col-12 col-md-6 col-xl-4 offset-sm-0 offset-md-3 offset-xl-4">
            <div class="text-center text-secondary">
                <h4>Painting ID: <span class="text-primary">@Model.Painting.Id</span></h4><hr />
                <h4>Painting Name: <span class="text-primary">@Model.Painting.Name</span></h4><hr />
                <h4>Painting Author: <span class="text-primary">@Model.Painting.Author</span></h4><hr />
                <h4>Painting Genre: <span class="text-primary">@Model.Painting.Genre</span></h4><hr />
                <h4>Painting Price: <span class="text-primary">@Model.Painting.Cost</span></h4><hr />
                <img style="width: 50%" src=@photoPath asp-append-version="true" />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col text-center">
            <h5>Confirm deleting - @Model.Painting.Name ?</h5>

            <form method="post">
                <button type="submit" class="btn btn-danger">Delete</button>
                <a class="btn btn-primary" asp-page="/Paintings/Paintings">Go Back</a>
            </form>
        </div>
    </div>
</div>

PaintingStore/Pages/Paintings/Details.cshtml
@page "{id}"
@model PaintingStore.Pages.Paintings.DetailsModel
@{
    ViewData["Title"] = "Painting Details";
    var photoPath = $"/images/{Model.painting.Photopath ?? "noimage.png"}";
}

<div class="row m-3 justify-content-center">
    <div class="col col-lg-12 text-center p-5">
        <h1>@Model.painting.Name</h1>
        <h2 class="text-secondary"><ins>By @Model.painting.Author</ins></h2>
    </div>
    <div class="imageBox">
        <img class="card-img-top p-3" src=@photoPath asp-append-version="true" />
    </div>
    <div class="col col-lg-12">
        <div class="card">
            <div class="card-header">
                <h2><strong>Genre:</strong> @Model.painting.Genre</h2>
            </div>

            <div class="card-body">
                <h2><strong>Description:</strong>(will be soon)</h2>
            </div>

            <div class="card-footer">
                <h2 class="text-success"><strong class="text-dark">Price:</strong> @Model.painting.Cost $</h2>
            </div>
        </div>
    </div>
    <div class="m-4">
        <a class="btn btn-lg btn-dark m-1" asp-route-ID="@Model.painting.Id" asp-page="/Paintings/Edit">Edit</a>
        <a class="btn btn-lg btn-dark m-1" asp-route-ID="@Model.painting.Id" asp-page="/Paintings/Delete">Delete</a>
        <a class="btn btn-lg btn-dark m-1" asp-page="Paintings">Back</a>
    </div>
</div>

PaintingStore/Pages/Paintings/Edit.cshtml
@page "{id?}/{handler?}"
@using PaintingStore.Models;
@using PaintingStore.Services;
@model PaintingStore.Pages.Paintings.EditModel
@{
    var photoPath = $"/images/{Model.Painting.Photopath ?? "noimage.png"}";
    var pageTitle = "Create";

    if (Model.Paintings.Count() > 0)
    {
        pageTitle = Model.NewPaintingId > Model.MaxPaintingId ? "Create" : "Edit";
    }

    ViewData["Title"] = pageTitle;
}

<form method="post" class="mt-3" enctype="multipart/form-data">
    <!--Создаём скрытое поле для параметра ID-->
    <input type="hidden" asp-for="Painting.Id" />
    <input type="hidden" asp-for="Painting.Photopath" />

    <!--Добавляем поля редактирования-->
    <div class="row justify-content-center m-3">
        <div class="col col-lg-8">
            <div class="card">
                <div class="card-header text-center">
                    <!--Добавляем поле редактирования имени-->
                    <div class="form-group row">
                        <label asp-for="Painting.Name" class="col col-lg-4 col-form-label text-right">Edit Name:</label>
                        <div class="col col-lg-6">
                            <input asp-for="Painting.Name" class="form-control" placeholder="@Model.Painting.Name" />
                            <!--Добавляем сообщение валидации формы-->
                            <span asp-validation-for="Painting.Name" class="text-danger"></span>
                        </div>
                    </div>

                </div>
                <div class="card-body text-center">
                    <div class="row">
                        <div class="col col-lg-9">
                            <h4>Painting ID: @Model.Painting.Id</h4><hr />

                            <!--Добавляем поле редактирования автора-->
                            <div class="form-group row">
                                <label asp-for="Painting.Author" class="col col-lg-4 col-form-label text-right">Edit Author:</label>
                                <div class="col-12 col-lg-6">
                                    <input asp-for="Painting.Author" class="form-control mr-2" placeholder="@Model.Painting.Author" />
                                    <!--Добавляем сообщение валидации формы-->
                                    <span asp-validation-for="Painting.Author" class="text-danger"></span>
                                </div>
                            </div>
                            <hr />

                            <!--Добавляем поле редактирования цены-->
                            <div class="form-group row">
                                <label asp-for="Painting.Cost" class="col col-lg-4 col-form-label text-right">Edit Price:</label>
                                <div class="col-12 col-lg-6">
                                    <input asp-for="Painting.Cost" class="form-control mr-2" placeholder="@Model.Painting.Cost" />
                                    <!--Добавляем сообщение валидации формы-->
                                    <span asp-validation-for="Painting.Cost" class="text-danger"></span>
                                </div>
                            </div>
                            <hr />

                            <!--Добавляем поле редактирования жанра-->
                            <div class="form-group row">
                                <label asp-for="Painting.Genre" class="col col-lg-4 col-form-label text-right">Edit Genre:</label>
                                <div class="col-12 col-lg-6">
                                    <!--Создаём выпадающий список с департаментами-->
                                    <select asp-for="Painting.Genre" class="custom-select mr-2" asp-items="Html.GetEnumSelectList<Genre>()">
                                        <!--Добавляем начальный элемент выпадающего списка-->
                                        <option value="">Please Select</option>
                                    </select>
                                    <span asp-validation-for="Painting.Genre" class="text-danger"></span>
                                </div>
                            </div>
                            <hr />
                        </div>

                    </div>

                    <div class="col col-lg-3">
                        <div>

                            <img src="@photoPath" asp-append-version="true" />

                            <div class="custom-file">
                                <input asp-for="Photo" class="custom-file-input form-control" />
                                <label class="custom-file-label text-left">Click</label>
                            </div>

                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <div class="card-footer text-center" style="background-color: rgba(0, 0, 0, 0.25);">
                                <button type="submit" class="btn btn-success">Update</button>
                                <a asp-page="index" class="btn btn-danger">Cancel</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @section Scripts{
        <script>
            $(document).ready(function () {
                $('.custom-file-input').on("change", function () {
                    var fileName = $(this).val().split("\\").pop();
                    $(this).next('.custom-file-label').html(fileName);
                });
            });
        </script>

        <partial name="_ValidationScriptsPartial" />    
    }

</form>

PaintingStore/Pages/Paintings/Paintings.cshtml
@page
@model PaintingStore.Pages.Paintings.PaintingsModel
@{
    ViewData["Title"] = "Paintings";
}

<form class="mb-3" method="get">
    <div class="input-group">
        <input class="form-control" asp-for="SearchTerm"/>
        <div class="input-group-append">
            <button type="submit" class="btn btn-outline-dark">Search</button>
        </div>
    </div>
</form>

<div class="row">
    @foreach (var item in Model.Paintings)
    {
        var photoPath = $"/images/{item.Photopath ?? "noimage.png"}";

        <div class="col-4 col-lg-4 col-sm-1">
            <div class="card-deck">
                <div class="card m-3">
                    <div class="card-header text-center">
                        <h3>@item.Name</h3>
                    </div>

                    <div class="card-body text-center">
                        <img class="card-img-top" src=@photoPath asp-append-version="true" />
                    </div>

                    <div class="card-footer text-center">
                        <a class="btn btn-dark m-1" asp-route-ID="@item.Id" asp-page="/Paintings/Details">View</a>
                        <a class="btn btn-dark m-1" asp-page="/Paintings/Basket" asp-route-Id="@item.Id">Add</a>
                        <a class="btn btn-dark m-1" asp-route-ID="@item.Id" asp-page="/Paintings/Edit">Edit</a>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

PaintingStore/Pages/Paintings/Stats.cshtml
@page
@model PaintingStore.Pages.Paintings.StatsModel
@{
}

<div class="row m-3 justify-content-center">
    <div class="col col-lg-8">
        @await Component.InvokeAsync("PaintCount")
    </div>
</div>